import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Brain, Target, TrendingUp, Shield } from 'lucide-react-native';

const featuresSection = [
    {
        icon: Brain,
        title: 'AI-Powered Questions',
        description: 'Dynamic questions generated by advanced AI based on your job requirements',
        gradient: ['#667eea', '#764ba2']
    },
    {
        icon: Target,
        title: 'Personalized Assessment',
        description: 'Tailored interviews matching your experience level and skills',
        gradient: ['#f093fb', '#f5576c']
    },
    {
        icon: TrendingUp,
        title: 'Real-time Feedback',
        description: 'Instant scoring and detailed feedback to improve your performance',
        gradient: ['#4facfe', '#00f2fe']
    },
    {
        icon: Shield,
        title: 'Secure & Private',
        description: 'Your data is encrypted and securely stored with enterprise-grade security',
        gradient: ['#43e97b', '#38f9d7']
    }
];

export default function FeaturesSection() {
    return (
        <View style={styles.featuresSection}>
            <View style={styles.sectionHeader}>
                <Text style={styles.sectionTitle}>Why Choose Our Platform?</Text>
                <Text style={styles.sectionSubtitle}>
                    Experience the future of interview preparation with cutting-edge AI technology
                </Text>
            </View>

            <View style={styles.featuresGrid}>
                {featuresSection.map((feature, index) => {
                    const IconComponent = feature.icon;
                    return (
                        <View key={index} style={styles.featureCard}>
                            <LinearGradient
                                colors={feature.gradient as [string, string, ...string[]]}
                                style={styles.featureIconContainer}
                            >
                                <IconComponent size={28} color="white" />
                            </LinearGradient>
                            <View style={styles.featureContent}>
                                <Text style={styles.featureTitle}>{feature.title}</Text>
                                <Text style={styles.featureDescription}>{feature.description}</Text>
                            </View>
                        </View>
                    );
                })}
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    featuresSection: {
        paddingVertical: 80,
        paddingHorizontal: 24,
        backgroundColor: '#0a0a0a',
    },
    sectionHeader: {
        alignItems: 'center',
        marginBottom: 60,
    },
    sectionTitle: {
        fontSize: 36,
        fontFamily: 'Inter-Bold',
        color: 'white',
        textAlign: 'center',
        marginBottom: 16,
    },
    sectionSubtitle: {
        fontSize: 18,
        color: 'rgba(255, 255, 255, 0.7)',
        textAlign: 'center',
        maxWidth: 600,
        lineHeight: 28,
        fontFamily: 'Inter-Regular',
    },
    featuresGrid: {
        gap: 24,
    },
    featureCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderRadius: 20,
        padding: 32,
        flexDirection: 'row',
        alignItems: 'flex-start',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    featureIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 24,
    },
    featureContent: {
        flex: 1,
    },
    featureTitle: {
        fontSize: 20,
        fontFamily: 'Inter-Bold',
        color: 'white',
        marginBottom: 8,
    },
    featureDescription: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.7)',
        lineHeight: 24,
        fontFamily: 'Inter-Regular',
    },
});
